version: '2.4'

services:
  letsencrypt:
    image: maksimstojkovic/letsencrypt
    container_name: letsencrypt
    volumes:
      - ./certs:/etc/letsencrypt
    environment:
      - LETSENCRYPT_DOMAIN= #optional
      - LETSENCRYPT_WILDCARD=false #optional
      - LETSENCRYPT_EMAIL= #optional
      - TESTING=false #optional
      - UID=0 #optional
      - GID=0 #optional
    restart: unless-stopped
